### ISSUE TITLE
Mention number of EIP drafts that were submitted but not merged in EIPs Insight

### ISSUE THREAD

**Issue by Pandapip1** [ethereum-cat-herders/EIPIP#115]
https://hackmd.io/@poojaranjan/EthereumImprovementProposalsInsight mentions the number of merged drafts, but not the number of PRs submitted that add new EIP files and the number of draft EIPs waiting to be merged. It would also be nice to have a breakdown of the category (ERC, core, etc...) of the drafts that were merged, and the drafts that are currently pending approval.

**Comment by poojaranjan** [comment]
@Pandapip1 thanks for sharing improvement suggestions.

> nice to have a breakdown of the category (ERC, core, etc...) of the drafts that were merged

I will have it added for the month of March and onward

>  drafts that are currently pending approval

Do you seem to have any specific thought in mind as why people will be interested in data for open PR with an improvement proposal before merge as "Draft"?

I can't seem to find a good reason to have this data included unless they are useful to a certain set of people. Because not all of them end up merged and unless merged there is no need for community review and/or feedback. 

Happy to add to the next EIPIP meeting to collect more thoughts on this.

**Comment by Pandapip1** [comment]
> I can't seem to find a good reason to have this data included

It would be nice to compare the number of PRs opened in a specific track to the number that are being merged for that track. Notably, it could signal a problem if the former is much larger than the latter.

**Comment by poojaranjan** [comment]
The [EIPs Insight for March 2022](https://hackmd.io/@poojaranjan/EthereumImprovementProposalsInsight/https%3A%2F%2Fhackmd.io%2F%40poojaranjan%2FEIPsInsightMarch2022) has additional information as requested. 
Thanks for the suggestion, @Pandapip1, we hope to continue sharing.

**Comment by poojaranjan** [comment]
Feel free to close the issue if you think it has been addressed.
