### ISSUE TITLE
EIP-4907 has inconsistencies with EIP-721 but it is flagged final and hence cannot be changed?

### ISSUE THREAD

**Issue by TimDaub** [ethereum-cat-herders/EIPIP#156]
- e.g. I have found an inconsistency that would have been nice to resolve in EIP-4907: https://ethereum-magicians.org/t/eip4907-erc-721-user-and-expires-extension/8572/17?u=timdaub
- but it seems the standard is flagged as final. So will we now have to permanently live with this inconsistency?
- it'd be nice if there was an opinion for recourse somehow...

**Comment by Pandapip1** [comment]
There actually is an option, although it certainly isn't ideal. One can simply make a new EIP by modifying the old one. The upside is that everyone is happy and can choose which standard to implement. The downside is that now there are multiple competing standards.

So:
- Inconsistencies are fine as long as they don't cause any contradictions
- EIP-4907 will permanently have that inconsistency, but if new standards are proposed, you may feel free to choose whichever you prefer.
- A new EIP that is more consistent with EIP-721 may be created. All EIPs are CC0-licenced, so authors may make whatever changes most please them.

**Comment by poojaranjan** [comment]
The issue was discussed in the [EIPIP meeting 60](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20060.md). The above recommendation of "One can simply make a new EIP by modifying the old one" is the general recommendation. 

Feel free to create a Pull Request with changes to the existing EIP.
