### ISSUE TITLE
EIPIP Meeting 82

### ISSUE THREAD

**Issue by SamWilsn** [ethereum-cat-herders/EIPIP#235]
# Date and Time

May 31, 2023 at 14:00 UTC
# Location

Zoom: TBA in the Discord #eip-editing channel

YouTube Live Stream/Recording: https://www.youtube.com/playlist?list=PL4cwHXAawZxpLrRIkDlBjDUUrGgF91pQw

# Agenda
### 1. Discuss Open Issues/PRs, and other topics

* [x] Patents: https://github.com/ethereum/EIPs/pull/6956#discussion_r1198121170 
* [x] Issue with Auto Review bot [Ref. here](https://discord.com/channels/916516304972824576/916713912970412103/1113084522175676496)
* [x] https://github.com/ethereum/EIPs/issues/7064
* [x] [ERC's status advancement criteria](https://ethereum-magicians.org/t/discussion-of-guideline-for-advancing-eip-status-a-straw-man-proposal/11995) Ref: [Comment](https://github.com/ethereum-cat-herders/EIPIP/issues/232#issuecomment-1551560336)
#### Changes to `Final` proposal
* [x] https://github.com/ethereum/EIPs/pull/7077

### 3. EIPs Insight - Monthly EIPs status reporting.

* [Hackmd](https://hackmd.io/@poojaranjan/EthereumImprovementProposalsInsight/)

### 5. Review action items from earlier meetings
- [Summary](https://github.com/ethereum-cat-herders/EIPIP/issues/232#issuecomment-1551901068)

**Comment by poojaranjan** [comment]
## Summary
### 1. Discuss Open Issues/PRs, and other topics
####  Patents: [Add EIP: Asset-bound Non-Fungible Tokens ethereum/EIPs#6956 (comment)](https://github.com/ethereum/EIPs/pull/6956#discussion_r1198121170)
- Merged
 #### Issue with Auto Review bot [Ref. here](https://discord.com/channels/916516304972824576/916713912970412103/1113084522175676496)
- @SamWilsn didn't have updates since the bot was stopped last week
- @Pandapip1 was not on the call, may follow the recording later. 
- @lightclient suggested two improvements
    - Less notification from the bot
    - Merge PR by authors without the need to close and open 

#### Issues- [Issues with CL Link Validation ethereum/EIPs#7064](https://github.com/ethereum/EIPs/issues/7064)
- Gajinder, Victor, Greg are in favor of allowing PR in `Draft` whereas Sam & Matt had concerns. 
- General consensus is to probably allow specific links in `Draft` proposal and update EIPW bot to block when status changes to `Review` or beyond. 
- @g11tech added consensus [here](https://github.com/ethereum/EIPs/issues/7064#issuecomment-1570435765). He will add comments to respective EIPs' PR as well.

####  [ERC's status advancement criteria](https://ethereum-magicians.org/t/discussion-of-guideline-for-advancing-eip-status-a-straw-man-proposal/11995) Ref: [Comment](https://github.com/ethereum-cat-herders/EIPIP/issues/232#issuecomment-1551560336)
- @xinbenlv shared a quick presentation on **ERC Maturity (status)** [follow the recording]
- ERC should require 1 reference implementation
- Sam: not in favor, but not blocking
- Matt, same as Sam. Make a suggestion and not a requirement.
- @xinbenlv will make a PR to EIP-1 suggesting this change.

**Comment by SamWilsn** [comment]
> * General consensus is to probably allow specific links in `Draft` proposal and update EIPW bot to block when status changes to `Review` or beyond.

This was not the consensus on this topic. Instead we agreed to allow `https://github.com/ethereum/consensus-specs/compare/<from>...<to>` links in all statuses.

**Comment by xinbenlv** [comment]
@poojaranjan thank you for taking some note. Here is my summary, can you take a look if it's more precise?

1. @xinbenlv and @gcolvin in favor of adding implementation as requirement to advance.
2. @gcolvin is in favor of making "one implementation" for "Review" status as "MUST"
2. @lightclient think "requiring 3 is too much", agree to add "one implementation" for "Review" as "SHOULD" rather than "MUST"
3. @SamWilsn is not in favor nor blocking the proposal for adding "SHOULD have one implementation" to Review status. Without intention to block, Sam feels slightly negative towards the idea of requiring one implementation. Sam objects to requirement "multiple independent" implementations because motivated authors can created 3 implementations and fake them to look like "independent"
