### ISSUE TITLE
EIP-5000: Renumber to EIP-5159 (PR #5270) – Call for Transparency and Clean Rules

### ISSUE THREAD

**Issue by ProphetZX** [ethereum-cat-herders/EIPIP#284]
With regard to „EIP 5000: (PR #5270) Renumber to EIP-5159“, I would like to ask for a review and call for transparency with regard to what happened in these EIPs, issues, and pull requests. Unfortunately, reading the codified responses, it is hard to grasp for a less technically-inclined person such as myself, what exactly happened here.

https://github.com/ethereum/EIPs/pull/5270

Thank you!

Aperon

**Comment by SamWilsn** [comment]
The extremely short version (from memory, so things may be out of order or just wrong):

1. Pull request was opened by a bot waiting for number 5000. This was admitted by the EIP authors.
2. I assigned the number 4998 instead, since we try and discourage number sniping.
3. lightclient asked me in private if he could assign a different number.
4. Pull request was merged as EIP-5000.
5. Two other pull requests were opened, one to delete EIP-5000 and one to renumber it to EIP-5159.
6. Argument among EIP Editors ensued.
7. New decision making process ratified in [EIP-5069](https://eips.ethereum.org/EIPS/eip-5069).
8. https://github.com/ethereum-cat-herders/EIPIP/issues/274
9. Deadline elapsed.
10. As Keeper of Consensus, I determined the rough consensus to be "don't renumber", with:
    - In favour of renumbering: myself, xinbenlv, and g11tech.
        - it was number sniping.
        - one of the EIP authors is an editor, and should've been held to a higher standard.
        - [Broken Windows Theory](https://en.wikipedia.org/wiki/Broken_windows_theory).
        - Unfair to authors who didn't snipe, and to authors who sniped and were manually reassigned.
    - Opposed to renumbering: pandapip1, lightclient, gcolvin
        - Wasn't technically against the rules in EIP-1 at the time.
        - It's been so long it'll just cause more confusion now.
