### ISSUE TITLE
Splitting Out EIP repo into EIPs & ERCs

### ISSUE THREAD

**Issue by Souptacular** [ethereum-cat-herders/EIPIP#61]
At [EIPIP Meeting 29](https://github.com/ethereum-cat-herders/EIPIP/issues/57) we discussed splitting the EIPs repo into 2 repos with different editors at each: 1 for EIPs and 1 for ERCs. Here is what we have agreed upon so far. We have agreed we want to have EIP editors that are separate from ERC editors. We are still looking into how best to separate the repos, especially when it comes to how to number EIPs and ERCs going forward once they are separated.

**Comment by MicahZoltu** [comment]
**Goal**: Separate notification systems for ERC editors/subscribers and EIP editors/subscribers.
**Potential Solution**: Separate GitHub repositories so people can watch one repository or the other or both or neither.
**Potential Problem**: Numbering.  Some people expressed a desire to have EIP/ERC numbers be non-overlapping, which means there would be no EIP-20 and there would be no ERC-55.  This complicates number selection if we split into separate repositories.

**Comment by poojaranjan** [comment]
I think there is an option to customize a subscription for GitHub Notification, wondering if this will help following the proposal for issuing ERC numbers via EIP GitHub (Issue). 

IMO, the upside of this proposal 
- ERC number will not have to be started from scratch 
- there will never be a conflict of EIP & ERC numbers
- People visiting for EIPs will continue to get the visibility new of ERCs.

The only (maybe) downside is, the EIP repo will still have some room for ERCs but that would be limited to the Issue section. It shouldn't be a worry for people who don't want to pay attention to ERCs by opting for custom notifications. 

![image](https://user-images.githubusercontent.com/29681685/113911730-4aca3d80-97a8-11eb-80b2-5aabd11bb730.png)

**Comment by poojaranjan** [comment]
Adding options suggested for numbering in meeting 30

- Get engineering help to make a bot to check for collision 
- Get engineering help to design a web app that gives a number for EIP & ERC
- EIP & ERC editors manage through a spreadsheet
- EIP & ERC editors manage using a separate repo
- EIP & ERC editors use the EIP GitHub repo Issue section for grabbing ERCs number and the Pull Request section for EIP numbers

**Comment by MicahZoltu** [comment]
@poojaranjan For your suggestion, what would the content of the ERC reservation issue be?  Just placeholder text and we immediately close the issue?

**Comment by poojaranjan** [comment]
The way I look at it is the issue created in EIP GitHub by an ERC author is simply to request an ERC number. As soon as it is approved by the EIP/ERC editor, it can be closed. 

Rest all process will be the same as EIP, like creating a PR to request review and add finally merge the ERC. All these actions will be performed in the new ERC repository.

No PR will ever be requested in the EIP GitHub so technically it will never be merged to the EIP GitHub. There will not be any change in the current process except the placeholder for ERC proposals. The transition will be seamless IMO.

**Comment by jpitts** [comment]
Overall it is kind of a confusing situation to new develoeprs because ERCs are EIPs, as are Core EIPs, etc. 

Could we perhaps use a fork of ethereum/EIPs and call it ethereum/ERCs, and periodically sync between them? This would preserve the numbering and indicate which is the authoritative repo for all EIPs: the ethereum/EIPs. The other kinds of EIPs could also eventually fork and sync w/ the upstream repo.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by jpitts** [comment]
To make this notion a more formal proposal:

**Goal:** Separate notification systems for ERC editors/subscribers and EIP editors/subscribers.

**Potential Solution:** Maintain a top-level GitHub repo for all EIPs and facilitate the forking of GitHub repositories along "EIP type" so people can watch one repository or the other or both or neither.

**Potential Advantages:** Ability to scale to more developers and more kinds of Ethereum improvement, while maintaining a cohesive process. Every time a community emerges for proposing standards, a new type is added and a fork is created.

Potential Problems: Complexity, coordination, some need for central control / intervention. Who would manage the main EIPs repo? (probably the ECHs)

**Details**
- continue w/ the main ethreum/EIPs repo as is, but fork out ERCs and Core-EIPs, each w/ maintainers and editors
- add an index of EIPs (a README.md under https://github.com/ethereum/EIPs/tree/master/EIPS) so that each EIP can be easily found within its type directory
- create a technical and human process for periodically syncing between these repos, EIP bot would do a lot of the work here
- human process, plus web app or spreadsheet, for numbering for proposed numbering the incoming EIPs / ERCs

**Comment by MicahZoltu** [comment]
It is unclear to me what the advantage of starting with a fork are vs starting from scratch.  The ERCs repository would most likely diverge from the EIPs repository sufficiently to make merging upstream a very manual process.  For example, we probably would rewrite EIP-1 and the readme to be ERC focused, and we would probably want to rename the `EIPs` folder to `ERCs`.  We also likely would make changes to or totally scrap the Jekyll site from the fork.  Finally, we would likely delete all of the non ERC EIPs from the forked repository.  In the end, I don't think the ERC fork will align at all with the EIP base and we'll just end up bringing a bunch of unnecessary history with us into the new repository.

**Comment by jpitts** [comment]
Ok, this makes sense considering EIP-1 and the wish to diverge. Essentially this is a divorce in which assets are divided. This means that there will have to be a new EIP of that kind created for the ERCs, not EIP-1 as this must reside only in one place. It is as if there are Informational ERCs, and the first post-divorce ERC should be the EIP-1 equivalent w/ a new number.

**Comment by jpitts** [comment]
Yes ERC editors and stakeholders would need to form a new process for how its proposal pipeline works, how consensus is reached to move to each milestone, etc. This means a new file gets created and EIP-1 really only applies to Core EIPs.

**Comment by fulldecent** [comment]
**Proposal:**

Keep one repository. Two separate RSS feeds.

**Comment by poojaranjan** [comment]
> Yes ERC editors and stakeholders would need to form a new process for how its proposal pipeline works, how consensus is reached to move to each milestone, etc. This means a new file gets created and EIP-1 really only applies to Core EIPs.

Perhaps, the ERC process can be added to the README file of the new repository.

To me, it seems like the biggest challenge is to create a repo (https://github.com/ethereum/ERCs ) if there is no strong disagreement in creating one?

@jpitts could you suggest someone who can help with creating an ERC GitHub and probably grant access to the present EIP editors?

**Comment by poojaranjan** [comment]
> **Proposal:**
> 
> Keep one repository. Two separate RSS feeds.

I am not sure if RSS feed is being followed by a decent number of people.

**Comment by axic** [comment]
Is there a motivation listed somewhere how and why the split will be beneficent?

**Comment by poojaranjan** [comment]
> Is there a motivation listed somewhere how and why the split will be beneficial?

Good point!

I am not sure it is available in form of a document anywhere yet, but ECH will be publishing a blog to create awareness if and when the new process is approved and in action. 

For now, it is available in part in meeting notes [30](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20030.md#splitting-out-eip-repos-into-eips--ercs), [31](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20031.md#1-splitting-out-eip-repos-into-eips--ercs-ref-issue), and this issue.

**Comment by fulldecent** [comment]
Surely more people can be bothered to subscribe to an RSS feed that to create a GitHub account and read every issue in a repo.

Trust me, I've tried.

---

I do not support making a new repo. The threshold for a new repo should be people that write non-ERC EIPs saying they don't want others in their playground.

---

But to reduce noise, I do recommend turning off issues in the EIPs repo and turning on discussions. And listing GitHub Discussions as the official place where EIP discussions should take place.

We have a problem. GitHub solved the problem. GitHub are nice people. Let's use their solution.

**Comment by axic** [comment]
Thanks @poojaranjan!

30 starts with saying "Pooja introduces the topic, which stems from the decision made in the previous meeting". [29](https://github.com/ethereum-cat-herders/EIPIP/blob/master/All%20EIPIP%20Meetings/Meeting%20029.md#2-should-ercs-be-moved-to-a-separate-repo) apparently lists the main problem of EIP editors not being familiar with the content of ERCs and not being capable of conducting their duties of review properly.

I really wonder if that just means that more editors (including ERC editors) could be added to the EIP repository and based on a proper conduct "ERC editors" not familiar with Core EIPs will not approve such changes, and EIP editors not familiar with ERCs will not approve those. Wasn't the main argument always that if an editor makes a (honest/malicious) mistake it can always be easily reverted?

Second, probably the notion of EIP editors not being capable of ERCs stems from the core disagreement about the role of an editor. While probably it is not well described in EIP-1, the role was that of a person guiding and enforcing the formatting rules dictated by EIP-1. The role however did not include thorough technical review capability of the content. The Review / Last Call state supposed to accomplish that by inviting interested parties.

If the role of the editor is purely for guiding through the process and ensuring formatting rules, then both "EIP editors" and "ERC editors" should be capable of reviewing any "EIP/ERC".

**Comment by poojaranjan** [comment]
It is clear that the number of active editors to review EIPs and ERCs is really low and adding more editors is very much needed. We've published a [post inviting participation to become an EIP editor](https://medium.com/ethereum-cat-herders/become-an-eip-editor-337f4376bf29).  The challenging part is the interested applicant has to be familiar with the current process and best if he/she has actually participated in the process at some point in time. Hopefully, we get more people to volunteer. 

As it appears to me, the bigger issue than "not being capable of reviewing ERCs" is actually "not having a bandwidth of reviewing both ERCs & EIPs". As one of the reviewers dropped looking into ERCs, the number of open PRs started to getting higher. In long run, this will make it difficult for other editors to understand which PR needs to be reviewed and most of the ERC PR will be marked stale and eventually closed by the bot in absence of getting attention from editors. The current stats. of eips.ethereum.org suggest 113/141 ERC are in "Draft" status, obviously adding proposals that haven't been merged yet will increase the number. 

I understand, partially this can be taken care of by using labels but then it was highlighted that EIPs and ERCs are generally catering to different sets of users, so it would make sense to be separated. Those who are interested in getting feeds for EIPs should get EIP GitHub feeds and those who are interested in ERC repo feed can subscribe to ERC GitHub and those looking for both can subscribe to both of them. 

The main goal of splitting EIP & ERC into different repositories is to simplify things for actively involved people.  However, if the proposal of having a separate GitHub is having more downside than the advantage as expected, it is worth reconsidering. 

> the EIP/ERC editor role is not well described in EIP-1

Agreed, EIP-1 may need attention to describe the changes comprehensively.

**Comment by axic** [comment]
How does having a separate repository helps in getting more people involved in editing? I know this separation is a recurring topic, but have not seen any convincing answer so far how does it help in getting more editors.

As you mention some of the downsides are discussed above and in the notes (numbering conflicts, question of setup, etc.)

**Comment by poojaranjan** [comment]
> How does having a separate repository helps in getting more people involved in editing? I know this separation is a recurring topic, but have not seen any convincing answer so far how does it help in getting more editors.

@axic, you're correct, the separation is a recurring topic. I think, one of the driving forces behind this proposal is the [Discord conversation](https://discordapp.com/channels/595666850260713488/746566142700814426/821244976830611457) and perhaps @lightclient's interest to help with ERC PRs as editor. (Having someone in the picture is better than being blindsided). Once the ERC process is redefined and agreed upon, we can restart looking into more editors. As of now, I don't see separating guarantees more editors' participation.  

> As you mention some of the downsides are discussed above and in the notes (numbering conflicts, question of setup, etc.)

A possible solution has been identified for numbering conflicts and the process does not invite any major change except the GitHub repositories to request for an ERC number and submit a Pull Request to be merged. 

As per my understanding, the showstopper here is unawareness of people having the right access to create a repo in Ethereum GitHub.

**Comment by MicahZoltu** [comment]
> Keep one repository. Two separate RSS feeds.

For most people, it is far easier to subscribe to a GitHub notification email feed than it is to subscribe to an RSS feed.  Also, for EIP editors, we would need an RSS feed that essentially replicates the GitHub notification system, but filters out notifications related to ERCs which would require a non-trivial amount of engineering to get right.

**Comment by MicahZoltu** [comment]
> How does having a separate repository helps in getting more people involved in editing? I know this separation is a recurring topic, but have not seen any convincing answer so far how does it help in getting more editors.

If one wants to participate in EIP editing/reviewing, you would want to watch/subscribe to the EIPs repository.  If you do this today, your inbox is flooded with notifications for both EIPs and ERCs (along with a smattering of others).  Inversely, if you want to participate in ERC editing, you get a large volume of notifications you don't care about related to EIPs.

By splitting into two repositories, people can receive more targeted notifications specifically related to their area of interest, rather than being spammed by notifications that they have to manually filter (automated filtering of ERC/EIP is possible, but non-trivial).

----

Note: Even if we agree (which not everyone does) that EIP editing should be purely a bureaucratic process that could be fully automated or farmed out to low-skilled laborers, the problem of EIP *reviewers* is still present.

**Comment by lightclient** [comment]
There are many smart contract developers now who have little interested in the inner workings of the ethereum protocol. I'd love for them to have a place where they can collaboratively work on standards. There are also core developers who are mostly uninterested in the code running atop their clients. I would like for them to be able to monitor and review the latest proposed core changes without being inundated with ERCs.

There seem to be a few options:
* split out ERCs to their own repository
* improve rss feed to easily follow only core or ercs
* split core EIPs out to the eth1.0-specs repository
* do nothing

I prefer to transition to a spec-driven development process (similar to eth2), but I don't think we're ready for that yet as that would require us use the yellow paper as the canonical spec. My second preference is to split ERCs out into their own repository. I am having a little bit of cold feet on this now, because if we do move to a spec-driven dev process we'll no longer need the EIPs repository as a whole anyways. So it would've been better to just leave the ERCs where they are.

**Comment by ligi** [comment]
Nice to see this come to fruition!
For some historical context: https://github.com/ethereum/EIPs/issues/896

**Comment by anettrolikova** [comment]
I think ERCs doesn’t need to go to final stage in order to be implemented and used. I'm a fan of separating ERCs from EIPs repo and I would love to see it happen. Adding tags on ERCs would help sort them out and categorise so dApp devs can use them. I think ERCs are more of suggestions how dApps can be build, improving the logic of smart contracts in general. 

On behalf of Ethereum Magicians I would like to propose @wschwab as ERC editor who can help out separate ERCs and tag them with relevant category for example "wallets ", "token", "metadata"... I do think William should not do this work alone and have someone else help him out at least sorting and categorising ERCs would be helpful.

**Comment by lightclient** [comment]
@jpitts by "spec-driven" I mean via diffs against a canonical spec, the way the eth2 consensus changes are written.

**Comment by jpitts** [comment]
Ok, thanks for the claridication.

We do need to address the noise issue.

Again I go back to using git and GitHub. Why not use GitHub forks of the main EIPs repo for each Specs team? There would be specialized Editors and Herders for each type of system (Eth1, Eth2, Wallet, NFT, FungibleToken, etc).  Comments and changes to a PR happen on their fork of EIPs, and this is periodically sync'd back to the main EIPs repo.

**Comment by xinbenlv** [comment]
I fully support the discussion of whether or not to split ERC vs other EIPs. (I've not lean towards any side but think it's valuable to discuss).

To put into context, if the goal is to reduce notification burden, it came to my attention that **octobox.io** can support this query to filter ERC
https://octobox.io/?label=type%3A+ERC&repo=ethereum%2FEIPs
See 
<img width="1792" alt="2022-08-16_11-02-03" src="https://user-images.githubusercontent.com/640325/184912779-a4a8c379-6ad7-4cf8-a549-d3e1fc26bebc.png">

or filter out ERC https://octobox.io/?q=inbox%3Atrue+repo%3Aethereum%2FEIPs+-label%3A%22type%3A+ERC%22
<img width="1792" alt="2022-08-16_11-03-21" src="https://user-images.githubusercontent.com/640325/184913055-7f7edb4b-de16-4e36-b501-2833b014ebde.png">

While this feature is not natively supported by Github notification system yet, but I figure if a tool supports it, it might be supportable by future Github notification or other tools.

**Comment by lightclient** [comment]
lol

**Comment by poojaranjan** [comment]
Closing in light of [EIP-7329: ERC/EIP Repository split](https://eips.ethereum.org/EIPS/eip-7329)
